# Generated by Django 4.1.2 on 2022-10-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
