# Generated by Django 4.1.2 on 2022-10-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_family_player'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('Name', 'Team', 'Age', 'Sport')},
        ),
    ]
