# Generated by Django 4.1.2 on 2022-10-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=400)),
                ('StartDate', models.DateTimeField()),
                ('EndData', models.DateTimeField()),
            ],
        ),
    ]
