# Generated by Django 4.1.2 on 2022-10-13 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 10, 13, 7, 3, 26, 475886, tzinfo=datetime.timezone.utc))),
                ('end_data', models.DateTimeField(default=datetime.datetime(2022, 10, 13, 7, 3, 26, 475905, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
