# Generated by Django 4.1.2 on 2022-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_todolist_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
